version: "3.9"

services:
  dev:
    image: rumblekongleague/discord-bot
    env_file:
      - $PWD/.env
    # port 5000 is in use on Macs
    # so if someone wants to dev locally, they would have
    # to tinker with the port. Thus I set it to 5050
    # to avoid issues on Mac
    ports:
      - "5050"
    volumes:
      - $PWD:/bot
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

  watchtower:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "$HOME/.docker/config.json:/config.json:ro"
    ports:
      - "8080:8080"
    restart: always
    command: --label-enable --cleanup --interval 30
    networks:
      - web

networks:
  web:
